lexik_jwt_authentication:
    secret_key: '%kernel.project_dir%/config/jwt/private.pem' # Chemin vers votre clé privée
    public_key: '%kernel.project_dir%/config/jwt/public.pem'  # Chemin vers votre clé publique
    pass_phrase: 'votre-passphrase'                           # Passphrase de vos clés
    token_ttl: 3600  